### ISSUE TITLE
Finnish SMART profile isn't needed

### ISSUE THREAD

**Issue by jpriebe-epic** [fhir-fi/finnish-smart#23]
Josh Priebe from Epic here (jpriebe@epic.com). I work with Apotti and with our Epic standards group.

Related to this section of the guide:

> Why Do We Need to Profile the SMART Specification?
> The SMART App Launch specification is already a globally applicable specification. The International Patient Access specification adds some more constraints and details to it. Do we really need something more?
> We have found out that there are still some places in both of these specifications that allow some implementation feedom but may be tricky for app developers to support. In this implementation guide, we aim to provide clarity on topics like how an app best learns the organization or organization unit the practitioner launching the app works for (when launching the app).
> We believe we can get some of these details sorted out more efficiently in the local Finnish context. We still aim to feed our learnings and developments with the wider SMART community and help get parts of them adopted to the SMART and IPA specifications.

After review, the view of Epic is there isn't enough difference to the Finnish local context here to warrant an entirely new FHIR specification for Finnish SMART. The requirements seem duplicative to the base FHIR and SMART requirements. Further drift from global standards will make support harder for global actors. 

Rather, we recommend HL7.FI group should continue being an author and contributor to the global specifications being created.

**Comment by mrinnetmaki** [comment]
Well, there does not seem to be a lot of drift either, is there?

We at least want to mandate JSON as content format (leaving XML recommended and TTL optional).

Also, we have gotten requests from healthcare organizations to have some specification vetted by HL7 Finland that they could use in their tender processes. Just referring to the base SMART spec does not seem to fit them, for some reason. So there is a need for something like this.

We absolutely commit to doing our best not to drift from global standards and not to add any new requirements. The aim is merely to limit options.

We are also committed to continuing being an author and contributor to the global specs.

**Comment by jpriebe-epic** [comment]
Ok - understood than you for elaborating. 

Lets hope the drift stays limited and Epic's generic global SMART support continues to work in Finland.
